### ISSUE TITLE
wrong command in README.md

### ISSUE THREAD

**Issue by ginocomino** [yannclement/gnde#1]
$ chroot +x .dwm/autostart_blocking.sh
...
$ chroot +x .dwm/backlight.sh
...
$ chroot +x .dwm/status.sh

should be :

$ chmod +x .dwm/autostart_blocking.sh
...
$ chmod +x .dwm/backlight.sh
...
$ chmod +x .dwm/status.sh

**Comment by yannclement** [comment]
Absolutely, thanks.
