### ISSUE TITLE
add Function key modifier in config.h

### ISSUE THREAD

**Issue by ginocomino** [yannclement/gnde#2]
To add the missing "Fn" key modifier simply add in config.h

#define FUNCKEY Mod5Mask

and use it as you like it, i.e.:

...
{ FUNCKEY,XK_Escape,spawn,{.v = shutdown } },
{ FUNCKEY,XK_b,spawn,{.v = brightdown }
...

**Comment by yannclement** [comment]
It works ! Thank you !
